---
- name: Log Linux distro
  debug:
    msg: "Provisioning k3s controller node"


- name: Install k3s controller.
  shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644

- name: Controller node token
  shell: cat /var/lib/rancher/k3s/server/token
  register: k3s_token


- name: Echo k3s token
  debug:
    msg: "{{ k3s_token.stdout }}"

- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name:   "k8s_token_holder"
    token:  "{{ k3s_token.stdout }}"
    ip:  "{{ ansible_host }}"

- name: Install dashboard
  shell: |
    GITHUB_URL=https://github.com/kubernetes/dashboard/releases
    VERSION_KUBE_DASHBOARD=$(curl -w '%{url_effective}' -I -L -s -S ${GITHUB_URL}/latest -o /dev/null | sed -e 's|.*/||')
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/${VERSION_KUBE_DASHBOARD}/aio/deploy/recommended.yaml
