all:
  children:
    rockpi: ### aka controller. used for init setup
      hosts:
        berry-controller-1.local:
          ansible_connection: ssh
          ansible_ssh_user: rock
          ansible_ssh_pass: rock
          ansible_sudo_pass: rock
          ansible_host: 192.168.178.75
          ansible_host_key_checking: false
          ansible_remote_tmp: /tmp
    raspberry:
      hosts:
        berry-worker-1.local:
          ansible_connection: ssh
          ansible_user: pi
          ansible_host_key_checking: false
          ansible_host: 192.168.178.56
          ansible_remote_tmp: /tmp
        berry-worker-2.local:
          ansible_connection: ssh
          ansible_user: pi
          ansible_host_key_checking: false
          ansible_host: 192.168.178.55
          ansible_remote_tmp: /tmp
        berry-worker-3.local:
          ansible_connection: ssh
          ansible_user: pi
          ansible_host_key_checking: false
          ansible_host: 192.168.178.57
          ansible_remote_tmp: /tmp
    ubuntu:
      hosts:
        frontend-pi.local:
          ansible_ssh_user: ubuntu
          ansible_ssh_pass: ubuntu_pass
          ansible_sudo_pass: ubuntu_pass
          ansible_host: 192.168.178.59
          ansible_host_key_checking: false
          ansible_remote_tmp: /tmp
